### ISSUE TITLE
New Resource element issue in presentation mode

### ISSUE THREAD

**Issue by Marco-Dos** [primaryapp/primary.app#2]
Hi,

it looks like something goes wrong when adding a resource to a flow step; once I do that, on presentation mode I get as follows:

![Screenshot 2019-12-05 at 16 37 16](https://user-images.githubusercontent.com/24223100/70251318-8f426500-177f-11ea-8eaa-099f90c58f75.png)

if I remove the resource element, everything gets back to normal; can you check?
Ciao,

**Comment by primaryapp** [comment]
Hi @Marco-Dos,
We can replicate that, I'm creating an issue to do a hot-fix.  We'll report back here when it's done.
