### ISSUE TITLE
Updating Sketch plugin from 0.4 to 0.5 (Issue)

### ISSUE THREAD

**Issue by cheyneosy** [primaryapp/primary.app#3]
@primaryapp 

I was noticing a reoccurring issue when it comes to updating the Primary Sketch plugin. I'm currently running 0.4 and have been getting notifications to update to 0.5. For some reason, anytime I hit "update", it does not try to fetch the update at all. Not sure if anyone else has this same issue, but I thought I'd mention it!

<img width="469" alt="Screen Shot 2020-01-06 at 9 12 52 AM" src="https://user-images.githubusercontent.com/5694327/71823263-d4023a00-3064-11ea-8620-4a9722afa8e9.png">

**Comment by bfconsult** [comment]
This has been fixed.
