### ISSUE TITLE
Go one flow into another

### ISSUE THREAD

**Issue by ildarsharafutdinov** [primaryapp/primary.app#4]
hi,

Is there a way to make a step to be a flow?

Let's say I have 2 flows:
- `select a photo from gallery` 
- `create profile`

What I want is to add a step to `create profile`, that would take user to `select a photo from gallery`.
Is it possible?

**Comment by bfconsult** [comment]
Linking between flows is not a feature for a specific reason.   The reason for that we don't have such a thing is:
1. The resulting model becomes a tangle of interlinked flows, which is very hard for anyone but the author to understand.  The key aim of the model is that it can be easily understood by other team members and stakeholders, so it has to be kept simple.
2. Each flow should be written to stand on its own.  Each flow should achieve a useful user goal.  Interlinking flows will result in some flows becoming a small re-usable piece.  In this case, the flow no longer is self-contained.
