### ISSUE TITLE
Clicking on "Use External Image URL" button and then clicking "X" deletes current image

### ISSUE THREAD

**Issue by boxxxie** [primaryapp/primary.app#5]
![image](https://user-images.githubusercontent.com/440034/84834548-a2bc6b80-afff-11ea-9fde-f3e28dfd3cf8.png)
![image](https://user-images.githubusercontent.com/440034/84834583-b962c280-afff-11ea-83a1-6c18e3f1ad87.png)

**Comment by bfconsult** [comment]
This MVP implementation has been completely re-written.
