### ISSUE TITLE
Issue copying Elements

### ISSUE THREAD

**Issue by Cedric-Delanchy** [primaryapp/primary.app#6]
I created an 'account creation form' elements with basic labels. 

I want to copy that form in the data tab using "Copy to new data" option.

Whil I'm clicking I have the following issue 'exception: Undefined index: project_ext' popping.

I tried doing it in both ways Form > Data and Data > Form.

**Comment by bfconsult** [comment]
Bug confirmed, fixed and released as a hot-fix.
